### ISSUE TITLE
Test compiled javascript instead of coffeescript

### ISSUE THREAD

**Issue by adborden** [duereg/laboratory#4]
People have their own preferences on this one. I've got a PR if you're interested.

- ignore lib/
- build js in pretest
- require lib/ in specs

**Comment by duereg** [comment]
@adborden all the changes you requested have been merged, I've bumped the version to 1.0.0 as well. 

Tell everyone I said hi! Well, almost everyone. :)

**Comment by adborden** [comment]
;D
